const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event5_Act2,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetDefaultControls,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.MoveToTop
	];
};
self.C3_JsPropNameTable = [
	{fundo: 0},
	{fundo2: 0},
	{Sólido: 0},
	{chao: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{pIxy: 0},
	{Teclado: 0},
	{Sprite11: 0},
	{fragSonho1: 0},
	{plataform: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Senóide: 0},
	{slime: 0},
	{fragsonho2: 0},
	{fragsonho3: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite10: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite22: 0},
	{fragsonho4: 0},
	{slime2: 0},
	{Sprite: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0}
];

self.InstanceType = {
	fundo: class extends self.ISpriteInstance {},
	fundo2: class extends self.ISpriteInstance {},
	chao: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	pIxy: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	fragSonho1: class extends self.ISpriteInstance {},
	plataform: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	slime: class extends self.ISpriteInstance {},
	fragsonho2: class extends self.ISpriteInstance {},
	fragsonho3: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	fragsonho4: class extends self.ISpriteInstance {},
	slime2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {}
}